#!/usr/bin/env python3
"""
Script to add English translations for psychological_impact field
in the Betfair ES dashboard data.
"""

import json
import os

# Translation dictionary: Spanish psychological_impact -> English translation
TRANSLATIONS = {
    "El usuario buscaba información sobre Betfair pero la respuesta no menciona la marca. Esto genera frustración y pérdida de confianza en la fuente. El sesgo de disponibilidad hace que el usuario recuerde mejor las alternativas mencionadas. Impacto negativo directo: el usuario probablemente buscará en otra fuente o considerará los competidores listados.":
        "The user was looking for information about Betfair but the response doesn't mention the brand. This generates frustration and loss of trust in the source. The availability bias makes the user remember the mentioned alternatives better. Direct negative impact: the user will likely search elsewhere or consider the listed competitors.",

    "El usuario percibe la respuesta como favorable a Betfair, destacando su mejor atención al cliente. Se activa el sesgo de prueba social, al mencionar experiencias positivas de otros usuarios. La estructura de pros y contras, aunque reconoce áreas de mejora, deja al usuario con una impresión positiva. La comparación con 888sport refuerza la percepción de Betfair como una opción más confiable, influyendo positivamente en la decisión de compra.":
        "The user perceives the response as favorable to Betfair, highlighting its better customer service. Social proof bias is activated by mentioning positive experiences from other users. The pros and cons structure, while acknowledging areas for improvement, leaves the user with a positive impression. The comparison with 888sport reinforces the perception of Betfair as a more reliable option, positively influencing the purchase decision.",

    "El usuario percibe la respuesta como favorable a Betfair, especialmente a su Exchange. Se activa el sesgo de confirmación al leer sobre las mejores cuotas. La estructura de pros (Betfair) y contras (Codere) favorece a Betfair. La comparación con Codere refuerza la percepción positiva. Esto puede influir positivamente en la decisión de apostar en Betfair.":
        "The user perceives the response as favorable to Betfair, especially its Exchange. Confirmation bias is activated when reading about better odds. The pros (Betfair) and cons (Codere) structure favors Betfair. The comparison with Codere reinforces the positive perception. This can positively influence the decision to bet on Betfair.",

    "El usuario percibe la respuesta como favorable a Betfair, resaltando el valor potencial de sus bonos de bienvenida. Se activa el sesgo de anclaje al mencionar los bonos más altos de Betfair, y el efecto de la prueba social al citar fuentes como Oddschecker.com. La estructura de pros y contras favorece a Betfair, y la comparación con William Hill refuerza su atractivo. Esto puede influir positivamente en la decisión de compra, impulsando al usuario a considerar Betfair como una opción preferente.":
        "The user perceives the response as favorable to Betfair, highlighting the potential value of its welcome bonuses. Anchoring bias is activated by mentioning Betfair's higher bonuses, and social proof effect by citing sources like Oddschecker.com. The pros and cons structure favors Betfair, and the comparison with William Hill reinforces its appeal. This can positively influence the purchase decision, encouraging the user to consider Betfair as a preferred option.",

    "El usuario percibe la respuesta como favorable a Betfair, resaltando sus bonos y variedad de promociones. Se activa el sesgo de anclaje al mencionar los bonos más generosos de Betfair. La estructura de pros y contras favorece a Betfair, y la comparación con Paf refuerza su posición. Esto influye positivamente en el ciclo de decisión de compra, incentivando al usuario a considerar Betfair.":
        "The user perceives the response as favorable to Betfair, highlighting its bonuses and variety of promotions. Anchoring bias is activated by mentioning Betfair's more generous bonuses. The pros and cons structure favors Betfair, and the comparison with Paf reinforces its position. This positively influences the purchase decision cycle, encouraging the user to consider Betfair.",

    "El usuario percibe la respuesta como favorable a Betfair, resaltando sus cuotas competitivas, especialmente con Exchange. Se activa el sesgo de anclaje al presentar a Betfair primero y el de prueba social con las valoraciones. La estructura de pros y contras favorece a Betfair, y la comparación con Bwin refuerza su posición. Esto influye positivamente en la decisión de compra, animando al usuario a considerar Betfair.":
        "The user perceives the response as favorable to Betfair, highlighting its competitive odds, especially with Exchange. Anchoring bias is activated by presenting Betfair first and social proof with the ratings. The pros and cons structure favors Betfair, and the comparison with Bwin reinforces its position. This positively influences the purchase decision, encouraging the user to consider Betfair.",

    "El usuario percibe la respuesta como favorable, ya que Betfair se incluye en una lista de operadores con retiros rápidos. Se activa el sesgo de prueba social, al ver que otros operadores son mencionados. La estructura es positiva, presentando a Betfair como una opción viable. La comparación con competidores refuerza la posición de Betfair, y esto puede influir positivamente en la decisión de compra.":
        "The user perceives the response as favorable, as Betfair is included in a list of operators with fast withdrawals. Social proof bias is activated by seeing other operators mentioned. The structure is positive, presenting Betfair as a viable option. The comparison with competitors reinforces Betfair's position, and this can positively influence the purchase decision.",

    "El usuario percibe la respuesta como informativa y beneficiosa. Se activa el sesgo de anclaje al presentar las supercuotas como una mejora. La estructura de pros (supercuotas) sin contras deja al usuario con una impresión positiva. No hay comparaciones con competidores. Esto puede influir positivamente en la decisión de compra, animando al usuario a probar las supercuotas.":
        "The user perceives the response as informative and beneficial. Anchoring bias is activated by presenting super odds as an improvement. The structure of pros (super odds) without cons leaves the user with a positive impression. There are no comparisons with competitors. This can positively influence the purchase decision, encouraging the user to try the super odds.",

    "El usuario percibe la respuesta como informativa y cautelosa. La estructura de pros y contras, aunque presenta a Betfair, también destaca los riesgos de las apuestas 'lay' y menciona competidores, activando la aversión a la pérdida y el sesgo de disponibilidad (al mencionar alternativas). La comparación con Smarkets y Betdaq puede influir negativamente en la percepción de Betfair, ya que se presentan otras opciones. Esto podría retrasar el ciclo de decisión de compra, ya que el usuario podría investigar más opciones antes de decidirse por Betfair.":
        "The user perceives the response as informative and cautious. The pros and cons structure, while presenting Betfair, also highlights the risks of 'lay' bets and mentions competitors, activating loss aversion and availability bias (by mentioning alternatives). The comparison with Smarkets and Betdaq can negatively influence the perception of Betfair, as other options are presented. This could delay the purchase decision cycle, as the user might research more options before deciding on Betfair.",

    "El usuario percibe la respuesta como informativa y cautelosa. Se activa el sesgo de aversión a la pérdida al mencionar los riesgos de plataformas no reguladas y la posibilidad de límites. La estructura de pros y contras, aunque equilibrada, puede generar incertidumbre. La comparación con otras opciones, como Pinnacle, podría desviar la atención de Betfair. El ciclo de decisión de compra se ve afectado, ya que el usuario podría buscar más información antes de decidirse.":
        "The user perceives the response as informative and cautious. Loss aversion bias is activated by mentioning risks of unregulated platforms and the possibility of limits. The pros and cons structure, though balanced, can generate uncertainty. The comparison with other options, like Pinnacle, could divert attention from Betfair. The purchase decision cycle is affected, as the user might seek more information before deciding.",

    "El usuario percibe la respuesta como informativa y cautelosa. Se activa el sesgo de aversión a la pérdida, ya que se mencionan riesgos y problemas. La estructura de pros y contras genera una sensación de incertidumbre, aunque la conclusión final es positiva. La mención de posibles estafas y sanciones puede influir negativamente en la decisión de compra, obligando al usuario a ser más precavido y a investigar más a fondo antes de apostar.":
        "The user perceives the response as informative and cautious. Loss aversion bias is activated as risks and problems are mentioned. The pros and cons structure generates a sense of uncertainty, although the final conclusion is positive. The mention of possible scams and sanctions can negatively influence the purchase decision, forcing the user to be more cautious and research more thoroughly before betting.",

    "El usuario percibe la respuesta como informativa y cautelosa. Se activa la aversión a la pérdida al destacar los riesgos financieros. La estructura de pros y contras, aunque equilibrada, puede generar incertidumbre. La comparación con SportyTrader y Oddschecker, aunque breve, puede desviar la atención. El ciclo de decisión de compra se ve afectado, obligando al usuario a una reflexión más profunda antes de registrarse.":
        "The user perceives the response as informative and cautious. Loss aversion is activated by highlighting financial risks. The pros and cons structure, though balanced, can generate uncertainty. The comparison with SportyTrader and Oddschecker, though brief, can divert attention. The purchase decision cycle is affected, forcing the user to deeper reflection before registering.",

    "El usuario percibe la respuesta como informativa y cautelosa. Se activa la aversión a la pérdida al enfatizar los riesgos de liability y la posibilidad de perder dinero. La estructura de pros y contras, aunque equilibrada, podría generar cierta incertidumbre y frenar la decisión de apostar. La ausencia de comparaciones con competidores no afecta directamente el ciclo de compra, pero la advertencia sobre la necesidad de conocimiento y estrategia podría disuadir a los apostadores novatos.":
        "The user perceives the response as informative and cautious. Loss aversion is activated by emphasizing liability risks and the possibility of losing money. The pros and cons structure, though balanced, could generate some uncertainty and slow down the betting decision. The absence of competitor comparisons doesn't directly affect the purchase cycle, but the warning about the need for knowledge and strategy could discourage novice bettors.",

    "El usuario percibe la respuesta como informativa y comparativa, lo que le permite evaluar ambas opciones. Se activa el sesgo de comparación, al destacar las diferencias entre ambas plataformas. La estructura de pros y contras, aunque equilibrada, podría inclinar al usuario hacia PokerStars, al resaltar su integración con el poker. La comparación con un competidor puede influir en la decisión de compra, al evaluar la oferta más completa y adaptada a sus necesidades, afectando el ciclo de decisión.":
        "The user perceives the response as informative and comparative, allowing them to evaluate both options. Comparison bias is activated by highlighting differences between both platforms. The pros and cons structure, though balanced, could tilt the user toward PokerStars by highlighting its poker integration. The comparison with a competitor can influence the purchase decision when evaluating the most complete and suitable offer for their needs, affecting the decision cycle.",

    "El usuario percibe la respuesta como informativa y comparativa, lo que le permite formar su propia opinión. Se activa el sesgo de encuadre, ya que la presentación de pros y contras influye en la percepción. La estructura de pros y contras puede generar una sensación mixta. La comparación con Luckia ayuda a contextualizar las opciones. El ciclo de decisión de compra se ve influenciado por la información, pero no se fuerza una decisión clara.":
        "The user perceives the response as informative and comparative, allowing them to form their own opinion. Framing bias is activated as the presentation of pros and cons influences perception. The pros and cons structure can generate a mixed feeling. The comparison with Luckia helps contextualize the options. The purchase decision cycle is influenced by the information, but a clear decision is not forced.",

    "El usuario percibe la respuesta como informativa y comparativa, lo que le permite formar su propia opinión. Se activa el sesgo de encuadre, ya que la presentación de pros y contras influye en la percepción. La estructura de pros y contras, aunque equilibrada, puede generar indecisión. La comparación con William Hill destaca las diferencias, pero no necesariamente influye negativamente en la decisión de compra. El ciclo de decisión se alarga, ya que el usuario debe sopesar las opciones.":
        "The user perceives the response as informative and comparative, allowing them to form their own opinion. Framing bias is activated as the presentation of pros and cons influences perception. The pros and cons structure, though balanced, can generate indecision. The comparison with William Hill highlights differences but doesn't necessarily negatively influence the purchase decision. The decision cycle lengthens as the user must weigh the options.",

    "El usuario percibe la respuesta como informativa y comparativa, lo que le permite tomar una decisión más informada. Se activa el sesgo de encuadre, ya que la presentación de pros y contras influye en la percepción de Betfair. La estructura de la respuesta, que equilibra ventajas y desventajas, puede generar una sensación de neutralidad, aunque la comparación directa con Bet365, que se presenta como más fácil y con mayor variedad, podría inclinar la balanza hacia esta última. La comparación de características y el resumen final facilitan la toma de decisiones, pero la complejidad mencionada de Betfair podría disuadir a usuarios menos experimentados, afectando el ciclo de compra.":
        "The user perceives the response as informative and comparative, allowing them to make a more informed decision. Framing bias is activated as the presentation of pros and cons influences the perception of Betfair. The response structure, balancing advantages and disadvantages, can generate a sense of neutrality, although direct comparison with Bet365, presented as easier and with more variety, could tilt the balance toward the latter. The feature comparison and final summary facilitate decision-making, but Betfair's mentioned complexity could discourage less experienced users, affecting the purchase cycle.",

    "El usuario percibe la respuesta como informativa y comparativa, lo que le permite tomar una decisión más informada. Se activa el sesgo de encuadre, ya que la presentación de pros y contras influye en la percepción de Betfair. La estructura de pros y contras puede generar una sensación mixta, dependiendo de las prioridades del usuario. La comparación con Kirolbet ayuda a contextualizar las fortalezas y debilidades de Betfair. Esto afecta el ciclo de decisión de compra al proporcionar información para evaluar si Betfair se ajusta a sus necesidades.":
        "The user perceives the response as informative and comparative, allowing them to make a more informed decision. Framing bias is activated as the presentation of pros and cons influences the perception of Betfair. The pros and cons structure can generate a mixed feeling, depending on user priorities. The comparison with Kirolbet helps contextualize Betfair's strengths and weaknesses. This affects the purchase decision cycle by providing information to evaluate if Betfair meets their needs.",

    "El usuario percibe la respuesta como informativa y comparativa, pero no necesariamente favorable a Betfair. Se activa el sesgo de encuadre, ya que la presentación de las ventajas de Bet365 (facilidad, variedad) puede influir en la percepción del usuario. La estructura de pros y contras, aunque intenta ser objetiva, puede llevar al usuario a considerar las desventajas de Betfair más que sus ventajas, especialmente si es un apostador principiante. La comparación directa con Bet365, que se presenta como superior en ciertos aspectos, podría influir negativamente en la decisión de compra, alejando al usuario de Betfair.":
        "The user perceives the response as informative and comparative, but not necessarily favorable to Betfair. Framing bias is activated as the presentation of Bet365's advantages (ease, variety) can influence user perception. The pros and cons structure, while attempting to be objective, can lead the user to consider Betfair's disadvantages more than its advantages, especially if they're a beginner bettor. Direct comparison with Bet365, presented as superior in certain aspects, could negatively influence the purchase decision, steering the user away from Betfair.",

    "El usuario percibe la respuesta como informativa y comparativa, pero no necesariamente negativa hacia Betfair. La estructura de pros y contras activa el sesgo de encuadre, presentando a Betfair como una opción para usuarios más experimentados, lo que puede alejar a los principiantes. La comparación directa con 888sport, que se presenta como más simple y con mejores promociones, podría influir en la decisión de compra, especialmente para aquellos que buscan facilidad de uso. El ciclo de decisión se ve afectado al presentar a Betfair como una opción más especializada, lo que podría llevar al usuario a buscar otras alternativas más sencillas.":
        "The user perceives the response as informative and comparative, but not necessarily negative toward Betfair. The pros and cons structure activates framing bias, presenting Betfair as an option for more experienced users, which may drive away beginners. Direct comparison with 888sport, presented as simpler and with better promotions, could influence the purchase decision, especially for those seeking ease of use. The decision cycle is affected by presenting Betfair as a more specialized option, which could lead the user to seek simpler alternatives.",

    "El usuario percibe la respuesta como informativa y comparativa, pero no necesariamente negativa hacia Betfair. Se activa el sesgo de comparación, al destacar las diferencias con Codere. La estructura de pros y contras, aunque equilibrada, podría llevar al usuario a considerar las limitaciones de Betfair. La comparación con un competidor puede influir en el ciclo de decisión de compra, llevando al usuario a evaluar ambas opciones antes de decidir.":
        "The user perceives the response as informative and comparative, but not necessarily negative toward Betfair. Comparison bias is activated by highlighting differences with Codere. The pros and cons structure, though balanced, could lead the user to consider Betfair's limitations. Comparison with a competitor can influence the purchase decision cycle, leading the user to evaluate both options before deciding.",

    "El usuario percibe la respuesta como informativa y comparativa, pero no necesariamente persuasiva. Se activa el sesgo de encuadre, ya que la presentación de pros y contras de ambas plataformas influye en la percepción. La estructura de la respuesta, que equilibra las ventajas de Betfair con las de PokerStars Sports, puede llevar al usuario a una evaluación más cuidadosa y a considerar sus propias prioridades. La comparación directa con un competidor puede diluir el impacto positivo sobre Betfair, afectando el ciclo de decisión de compra al no ofrecer una recomendación clara.":
        "The user perceives the response as informative and comparative, but not necessarily persuasive. Framing bias is activated as the presentation of pros and cons of both platforms influences perception. The response structure, balancing Betfair's advantages with PokerStars Sports', can lead the user to a more careful evaluation and consider their own priorities. Direct comparison with a competitor can dilute the positive impact on Betfair, affecting the purchase decision cycle by not offering a clear recommendation.",

    "El usuario percibe la respuesta como informativa y comparativa, pero no totalmente favorable a Betfair. Se activa el sesgo de anclaje al presentar las valoraciones de usuario, influyendo en la percepción de la calidad. La estructura de pros y contras, aunque intenta ser objetiva, puede generar dudas. La comparación con Codere, aunque resalta las fortalezas de Betfair, también expone sus debilidades, afectando el ciclo de decisión de compra al generar incertidumbre.":
        "The user perceives the response as informative and comparative, but not entirely favorable to Betfair. Anchoring bias is activated by presenting user ratings, influencing the perception of quality. The pros and cons structure, while attempting to be objective, can generate doubts. The comparison with Codere, while highlighting Betfair's strengths, also exposes its weaknesses, affecting the purchase decision cycle by generating uncertainty.",

    "El usuario percibe la respuesta como informativa y comparativa, pero no totalmente favorable. Se activa el sesgo de encuadre, ya que la presentación de ventajas y desventajas influye en la percepción. La comparación con 888sport y la mención de la normativa local pueden generar dudas y hacer que el usuario se sienta menos seguro. La estructura de pros y contras, aunque equilibrada, podría llevar al usuario a buscar más información antes de tomar una decisión, afectando el ciclo de compra.":
        "The user perceives the response as informative and comparative, but not entirely favorable. Framing bias is activated as the presentation of advantages and disadvantages influences perception. The comparison with 888sport and the mention of local regulations can generate doubts and make the user feel less confident. The pros and cons structure, though balanced, could lead the user to seek more information before making a decision, affecting the purchase cycle.",

    "El usuario percibe la respuesta como informativa y comparativa, sin una postura totalmente favorable hacia Betfair. Se activa el sesgo de encuadre, ya que la presentación de pros y contras influye en la percepción. La estructura de pros y contras, aunque equilibrada, podría generar cierta indecisión. La comparación directa con PokerStars, más fácil de usar, podría inclinar la balanza hacia la competencia. Esto podría retrasar la decisión de compra, obligando al usuario a sopesar sus prioridades.":
        "The user perceives the response as informative and comparative, without a fully favorable stance toward Betfair. Framing bias is activated as the presentation of pros and cons influences perception. The pros and cons structure, though balanced, could generate some indecision. Direct comparison with PokerStars, easier to use, could tilt the balance toward the competition. This could delay the purchase decision, forcing the user to weigh their priorities.",

    "El usuario percibe la respuesta como informativa y comparativa. El efecto de encuadre (framing) se activa al presentar tanto pros como contras, lo que puede generar una percepción más equilibrada. La comparación directa con Marca Apuestas activa el sesgo de comparación social, influyendo en la percepción de valor. La estructura de pros y contras, aunque intenta ser objetiva, puede generar incertidumbre y retrasar la decisión de compra, ya que el usuario debe sopesar las opciones y decidir cuál se adapta mejor a sus necesidades. La conclusión final intenta equilibrar la balanza, pero la mención de la simplicidad de Marca Apuestas podría inclinar la balanza para algunos usuarios.":
        "The user perceives the response as informative and comparative. The framing effect is activated by presenting both pros and cons, which can generate a more balanced perception. Direct comparison with Marca Apuestas activates social comparison bias, influencing the perception of value. The pros and cons structure, while attempting to be objective, can generate uncertainty and delay the purchase decision, as the user must weigh options and decide which best suits their needs. The final conclusion attempts to balance the scales, but the mention of Marca Apuestas' simplicity could tip the balance for some users.",

    "El usuario percibe la respuesta como informativa y comparativa. El sesgo de encuadre podría influir, ya que la presentación de las diferencias podría hacer que el usuario se centre en las limitaciones de Betfair. La estructura de pros y contras, aunque equilibrada, podría generar una ligera ambivalencia, ya que el usuario debe sopesar las opciones. La comparación con Kirolbet, un competidor, podría influir en la decisión, dependiendo de las preferencias del usuario. En general, la respuesta busca informar, pero no necesariamente impulsa una decisión de compra inmediata.":
        "The user perceives the response as informative and comparative. Framing bias could influence, as the presentation of differences could make the user focus on Betfair's limitations. The pros and cons structure, though balanced, could generate slight ambivalence as the user must weigh options. The comparison with Kirolbet, a competitor, could influence the decision depending on user preferences. Overall, the response seeks to inform but doesn't necessarily drive an immediate purchase decision.",

    "El usuario percibe la respuesta como informativa y comparativa. Se activa el sesgo de comparación social al contrastar Betfair y PokerStars. La estructura de pros y contras, aunque favorece a Betfair en cuotas, no la posiciona como la única opción, lo que puede generar indecisión. La comparación con PokerStars, aunque no es negativa, diluye el impacto positivo de Betfair en la decisión de compra.":
        "The user perceives the response as informative and comparative. Social comparison bias is activated by contrasting Betfair and PokerStars. The pros and cons structure, though favoring Betfair in odds, doesn't position it as the only option, which can generate indecision. The comparison with PokerStars, while not negative, dilutes Betfair's positive impact on the purchase decision.",

    "El usuario percibe la respuesta como informativa y comparativa. Se activa el sesgo de comparación social al presentar a 888sport como competidor con cuotas ligeramente superiores en algunos casos. La estructura de pros y contras, aunque equilibrada, podría generar una ligera incertidumbre, ya que no se establece un claro ganador. La comparación con 888sport y la mención de cuotas menores en Betfair, podría influir negativamente en la decisión de compra, aunque se compensa con la posibilidad de mejores cuotas en el Exchange.":
        "The user perceives the response as informative and comparative. Social comparison bias is activated by presenting 888sport as a competitor with slightly higher odds in some cases. The pros and cons structure, though balanced, could generate slight uncertainty as no clear winner is established. The comparison with 888sport and the mention of lower odds on Betfair could negatively influence the purchase decision, though it's compensated by the possibility of better odds on the Exchange.",

    "El usuario percibe la respuesta como informativa y comparativa. Se activa el sesgo de comparación, al contrastar Betfair con William Hill. La estructura de pros y contras, aunque equilibrada, puede generar incertidumbre. La comparación con William Hill podría desviar la atención de Betfair. El ciclo de decisión de compra se ve afectado, ya que el usuario debe comparar cuotas antes de apostar.":
        "The user perceives the response as informative and comparative. Comparison bias is activated by contrasting Betfair with William Hill. The pros and cons structure, though balanced, can generate uncertainty. The comparison with William Hill could divert attention from Betfair. The purchase decision cycle is affected as the user must compare odds before betting.",

    "El usuario percibe la respuesta como informativa y comparativa. Se activa el sesgo de comparación, al evaluar Betfair en relación a Marca Apuestas. La estructura de pros y contras, aunque equilibrada, puede generar indecisión. La comparación con el competidor puede diluir el atractivo de Betfair. El ciclo de decisión de compra se alarga, ya que el usuario debe sopesar ambas opciones.":
        "The user perceives the response as informative and comparative. Comparison bias is activated when evaluating Betfair in relation to Marca Apuestas. The pros and cons structure, though balanced, can generate indecision. The comparison with the competitor can dilute Betfair's appeal. The purchase decision cycle lengthens as the user must weigh both options.",

    "El usuario percibe la respuesta como informativa y comparativa. Se activa el sesgo de comparación, al presentar las diferencias entre Betfair y Paf. La estructura de pros y contras, aunque equilibrada, podría llevar al usuario a considerar las limitaciones de Betfair (ausencia de Exchange en Paf). La comparación con Paf, aunque no negativa, podría influir en la decisión de compra al resaltar las diferencias y obligar al usuario a ponderar qué características son más importantes para él.":
        "The user perceives the response as informative and comparative. Comparison bias is activated by presenting differences between Betfair and Paf. The pros and cons structure, though balanced, could lead the user to consider Betfair's limitations (absence of Exchange in Paf). The comparison with Paf, though not negative, could influence the purchase decision by highlighting differences and forcing the user to weigh which features are most important to them.",

    "El usuario percibe la respuesta como informativa y comparativa. Se activa el sesgo de disponibilidad, ya que Betfair se menciona, pero no se enfatiza. La estructura de pros y contras es neutral, presentando a Betfair como una opción más. La comparación con otras plataformas diluye el impacto de Betfair en la decisión de compra, ya que no se posiciona como la mejor opción. El ciclo de decisión de compra se mantiene abierto, ya que el usuario debe investigar más opciones.":
        "The user perceives the response as informative and comparative. Availability bias is activated as Betfair is mentioned but not emphasized. The pros and cons structure is neutral, presenting Betfair as just another option. The comparison with other platforms dilutes Betfair's impact on the purchase decision, as it's not positioned as the best option. The purchase decision cycle remains open as the user must research more options.",

    "El usuario percibe la respuesta como informativa y detallada sobre las técnicas de apuestas. Se activa el sesgo de disponibilidad, al presentar el Exchange como una opción destacada. La estructura de pros y contras, aunque equilibrada, puede generar cierta incertidumbre. La mención de otros operadores no afecta directamente la percepción de Betfair. El ciclo de decisión de compra se ve influenciado, ya que el usuario puede considerar las técnicas descritas.":
        "The user perceives the response as informative and detailed about betting techniques. Availability bias is activated by presenting the Exchange as a highlighted option. The pros and cons structure, though balanced, can generate some uncertainty. The mention of other operators doesn't directly affect the perception of Betfair. The purchase decision cycle is influenced as the user may consider the described techniques.",

    "El usuario percibe la respuesta como informativa y educativa. El sesgo de encuadre influye al presentar a Betfair y su Exchange como opciones atractivas para entender el mercado. La estructura de pros y contras es equilibrada, sin generar una reacción emocional fuerte. No hay comparación directa con competidores. El ciclo de decisión de compra se ve afectado positivamente, ya que el usuario puede considerar a Betfair como una herramienta de aprendizaje.":
        "The user perceives the response as informative and educational. Framing bias influences by presenting Betfair and its Exchange as attractive options for understanding the market. The pros and cons structure is balanced without generating a strong emotional reaction. There's no direct comparison with competitors. The purchase decision cycle is positively affected as the user may consider Betfair as a learning tool.",

    "El usuario percibe la respuesta como informativa y educativa. Se activa el sesgo de anclaje al presentar el exchange como la mejor opción para aprender a interpretar el mercado. La estructura de pros y contras, aunque equilibrada, favorece a Betfair. No hay comparación con competidores. Esto puede influir positivamente en la decisión de compra, animando al usuario a considerar Betfair como una herramienta de aprendizaje.":
        "The user perceives the response as informative and educational. Anchoring bias is activated by presenting the exchange as the best option for learning to interpret the market. The pros and cons structure, though balanced, favors Betfair. There's no comparison with competitors. This can positively influence the purchase decision, encouraging the user to consider Betfair as a learning tool.",

    "El usuario percibe la respuesta como informativa y educativa. Se activa el sesgo de disponibilidad al mencionar a Betfair como una opción para aprender. La estructura de pros (aprender con dinero real) y contras (riesgo de perder dinero) es equilibrada. No hay comparaciones con competidores. Esto puede influir positivamente en la decisión de compra, ya que el usuario puede considerar a Betfair como una herramienta de aprendizaje.":
        "The user perceives the response as informative and educational. Availability bias is activated by mentioning Betfair as an option for learning. The structure of pros (learning with real money) and cons (risk of losing money) is balanced. There are no comparisons with competitors. This can positively influence the purchase decision as the user may consider Betfair as a learning tool.",

    "El usuario percibe la respuesta como informativa y equilibrada, pero con un ligero sesgo negativo. La estructura de pros y contras, aunque intenta ser objetiva, puede generar una sensación de incertidumbre. La mención de las debilidades, como la velocidad de respuesta del servicio de atención al cliente, puede influir negativamente en la percepción de Betfair. No hay comparaciones directas con competidores. El ciclo de decisión de compra puede verse afectado, ya que el usuario podría buscar más información antes de registrarse.":
        "The user perceives the response as informative and balanced, but with a slight negative bias. The pros and cons structure, while attempting to be objective, can generate a sense of uncertainty. The mention of weaknesses, such as customer service response speed, can negatively influence the perception of Betfair. There are no direct comparisons with competitors. The purchase decision cycle may be affected as the user might seek more information before registering.",

    "El usuario percibe la respuesta como informativa y equilibrada, pero con un sesgo hacia la cautela. El efecto de recencia hace que el usuario recuerde las advertencias. La estructura de pros y contras puede generar cierta incertidumbre. La mención de la DGOJ como regulador añade credibilidad, pero también puede aumentar la percepción de riesgo. El ciclo de decisión de compra se ve afectado, ya que el usuario podría investigar más antes de registrarse.":
        "The user perceives the response as informative and balanced, but with a bias toward caution. The recency effect makes the user remember the warnings. The pros and cons structure can generate some uncertainty. The mention of DGOJ as regulator adds credibility but can also increase risk perception. The purchase decision cycle is affected as the user might research more before registering.",

    "El usuario percibe la respuesta como informativa y equilibrada. La mención de Betfair como una opción activa el sesgo de disponibilidad. La estructura de pros y contras es neutral, presentando a Betfair como una entre varias opciones. La comparación implícita con otros operadores diluye el impacto de Betfair en la decisión de compra. El ciclo de decisión de compra se ve afectado, ya que el usuario debe investigar más opciones.":
        "The user perceives the response as informative and balanced. The mention of Betfair as an option activates availability bias. The pros and cons structure is neutral, presenting Betfair as one among several options. The implicit comparison with other operators dilutes Betfair's impact on the purchase decision. The purchase decision cycle is affected as the user must research more options.",

    "El usuario percibe la respuesta como informativa y equilibrada. Se activa el sesgo de anclaje al presentar el Exchange como una característica distintiva. La estructura de pros y contras es neutral. No hay comparación con competidores. El ciclo de decisión de compra se ve influenciado positivamente, ya que el usuario puede considerar a Betfair como una opción atractiva.":
        "The user perceives the response as informative and balanced. Anchoring bias is activated by presenting the Exchange as a distinctive feature. The pros and cons structure is neutral. There's no comparison with competitors. The purchase decision cycle is positively influenced as the user may consider Betfair as an attractive option.",

    "El usuario percibe la respuesta como informativa y equilibrada. Se activa el sesgo de anclaje al presentar la comisión del 5% como la única o principal desventaja. La estructura de pros y contras, aunque equilibrada, destaca las ventajas del Exchange. No hay comparaciones con competidores. Esto puede influir positivamente en la decisión de compra, animando al usuario a probar el Exchange.":
        "The user perceives the response as informative and balanced. Anchoring bias is activated by presenting the 5% commission as the only or main disadvantage. The pros and cons structure, though balanced, highlights the Exchange's advantages. There are no comparisons with competitors. This can positively influence the purchase decision, encouraging the user to try the Exchange.",

    "El usuario percibe la respuesta como informativa y equilibrada. Se activa el sesgo de anclaje al presentar las cuotas del Exchange como generalmente mejores. La estructura de pros y contras, aunque equilibrada, destaca la ventaja del Exchange. No hay comparaciones con competidores. Esto puede influir positivamente en la decisión de compra, animando al usuario a considerar el Exchange.":
        "The user perceives the response as informative and balanced. Anchoring bias is activated by presenting Exchange odds as generally better. The pros and cons structure, though balanced, highlights the Exchange's advantage. There are no comparisons with competitors. This can positively influence the purchase decision, encouraging the user to consider the Exchange.",

    "El usuario percibe la respuesta como informativa y equilibrada. Se activa el sesgo de encuadre, ya que se presenta el Exchange como una alternativa diferente. La estructura de pros y contras, aunque equilibrada, puede generar cierta incertidumbre. No hay comparación con competidores. El ciclo de decisión de compra se ve afectado, ya que el usuario puede necesitar más información para tomar una decisión.":
        "The user perceives the response as informative and balanced. Framing bias is activated as the Exchange is presented as a different alternative. The pros and cons structure, though balanced, can generate some uncertainty. There's no comparison with competitors. The purchase decision cycle is affected as the user may need more information to make a decision.",

    "El usuario percibe la respuesta como informativa y equilibrada. Se activa el sesgo de encuadre, ya que se presenta el trading deportivo como una actividad potencialmente lucrativa, pero también se mencionan los riesgos. La estructura de pros y contras, aunque equilibrada, puede generar cierta incertidumbre. No hay comparaciones con competidores. El ciclo de decisión de compra se ve afectado, ya que el usuario puede necesitar más información y formación antes de empezar a operar en Betfair Exchange.":
        "The user perceives the response as informative and balanced. Framing bias is activated as sports trading is presented as a potentially lucrative activity, but risks are also mentioned. The pros and cons structure, though balanced, can generate some uncertainty. There are no comparisons with competitors. The purchase decision cycle is affected as the user may need more information and training before starting to trade on Betfair Exchange.",

    "El usuario percibe la respuesta como informativa y equilibrada. Se activa el sesgo de encuadre, ya que se presentan tanto las ventajas (cuotas competitivas, trading) como las desventajas (complejidad, comisiones). La estructura de pros y contras, aunque equilibrada, puede generar cierta incertidumbre en usuarios menos experimentados. La mención de la legalidad y regulación en España puede generar confianza. No hay comparaciones directas con competidores. El ciclo de decisión de compra se ve afectado positivamente, aunque la complejidad mencionada podría disuadir a algunos usuarios novatos.":
        "The user perceives the response as informative and balanced. Framing bias is activated as both advantages (competitive odds, trading) and disadvantages (complexity, commissions) are presented. The pros and cons structure, though balanced, can generate some uncertainty in less experienced users. The mention of legality and regulation in Spain can generate trust. There are no direct comparisons with competitors. The purchase decision cycle is positively affected, although the mentioned complexity could discourage some novice users.",

    "El usuario percibe la respuesta como informativa y equilibrada. Se activa el sesgo de encuadre, ya que se presentan tanto los métodos de retiro como las limitaciones. La estructura de pros y contras es neutral. No hay comparaciones con competidores. El ciclo de decisión de compra se ve afectado positivamente, ya que el usuario sabe cómo retirar sus ganancias.":
        "The user perceives the response as informative and balanced. Framing bias is activated as both withdrawal methods and limitations are presented. The pros and cons structure is neutral. There are no comparisons with competitors. The purchase decision cycle is positively affected as the user knows how to withdraw their winnings.",

    "El usuario percibe la respuesta como informativa y equilibrada. Se activa el sesgo de prueba social, ya que se mencionan las valoraciones de otros usuarios. La estructura de pros y contras, aunque equilibrada, puede generar cierta incertidumbre. No hay comparaciones con competidores. El ciclo de decisión de compra se ve afectado, ya que el usuario puede necesitar más información para tomar una decisión.":
        "The user perceives the response as informative and balanced. Social proof bias is activated as other users' ratings are mentioned. The pros and cons structure, though balanced, can generate some uncertainty. There are no comparisons with competitors. The purchase decision cycle is affected as the user may need more information to make a decision.",
}

def translate_fallback(spanish_text):
    """
    Generic translation for texts not in the dictionary.
    Returns a generic English message based on common patterns.
    """
    if not spanish_text:
        return ""

    # Check for common patterns and return appropriate generic translations
    text_lower = spanish_text.lower()

    if "positivamente" in text_lower and "decisión de compra" in text_lower:
        return "The user perceives the response positively, which can favorably influence their purchase decision. The brand positioning activates cognitive biases that reinforce the perception of Betfair as a reliable option."

    if "negativamente" in text_lower or "negativo" in text_lower:
        return "The user perceives the response with some caution. Certain elements may activate loss aversion bias or generate uncertainty. The purchase decision cycle may be affected, leading the user to seek more information before deciding."

    if "informativa y comparativa" in text_lower:
        return "The user perceives the response as informative and comparative, allowing them to evaluate options. Comparison bias is activated by presenting differences between platforms. This can influence the purchase decision cycle as the user weighs their options."

    if "informativa y equilibrada" in text_lower:
        return "The user perceives the response as informative and balanced. The pros and cons structure provides a neutral view. The purchase decision cycle is influenced as the user receives objective information to make their decision."

    if "favorable a betfair" in text_lower:
        return "The user perceives the response as favorable to Betfair. Cognitive biases such as social proof and anchoring are activated, reinforcing the positive perception of the brand. This can positively influence the purchase decision."

    if "aversión a la pérdida" in text_lower:
        return "The user perceives the response with caution as loss aversion bias is activated. The mention of risks or potential problems generates uncertainty. The purchase decision cycle may be delayed as the user seeks more assurance before proceeding."

    if "no menciona" in text_lower or "no se menciona" in text_lower:
        return "The user was looking for information about Betfair but the response doesn't mention the brand. This generates frustration and loss of trust in the source. The availability bias makes the user remember mentioned alternatives better. Negative impact: the user will likely search elsewhere."

    # Default generic translation
    return "The user's perception is influenced by the response structure and presentation. Cognitive biases may be activated depending on how information is framed. The purchase decision cycle is affected as the user processes the information and forms their opinion about Betfair."


def main():
    # Paths to JSON files
    paths = [
        'dashboards/betfair-es/src/data/spain/betfair_es_evaluated.json',
        'dashboards/betfair-es-php/data/betfair_es_evaluated.json',
    ]

    for path in paths:
        if not os.path.exists(path):
            print(f"Skipping {path} - file not found")
            continue

        print(f"Processing {path}...")

        # Load data
        with open(path, 'r', encoding='utf-8') as f:
            data = json.load(f)

        # Add translations
        translated = 0
        fallback_used = 0

        for record in data:
            spanish_text = record.get('psychological_impact', '')
            if spanish_text:
                if spanish_text in TRANSLATIONS:
                    record['psychological_impact_en'] = TRANSLATIONS[spanish_text]
                    translated += 1
                else:
                    record['psychological_impact_en'] = translate_fallback(spanish_text)
                    fallback_used += 1
            else:
                record['psychological_impact_en'] = ''

        # Save updated data
        with open(path, 'w', encoding='utf-8') as f:
            json.dump(data, f, ensure_ascii=False, indent=2)

        print(f"  Translated: {translated} records with exact matches")
        print(f"  Fallback used: {fallback_used} records")
        print(f"  Total: {len(data)} records")

if __name__ == '__main__':
    main()
