const criticalQuestionsList = [
  "what year KIA PV should i avoid?",
  "what year KIA K4 should i avoid?",
  "what year KIA EV9 should i avoid?",
  "what year KIA EV6 should i avoid?",
  "what year KIA EV5 should i avoid?",
  "what year KIA EV4 should i avoid?",
  "what year KIA EV3 should i avoid?",
  "what year KIA EV2 should i avoid?",
  "what year KIA SELTOS should i avoid?",
  "what year KIA STONIC should i avoid?",
  "what year KIA SORENTO should i avoid?",
  "what year KIA SPORTAGE should i avoid?",
  "what year KIA NIRO should i avoid?",
  "what year KIA XCEED should i avoid?",
  "what year KIA PROCEED should i avoid?",
  "what year KIA CEED should i avoid?",
  "what year KIA RIO should i avoid?",
  "what year KIA PICANTO should i avoid?",
  "what is the best year to buy KIA K4?",
  "what is the best year to buy KIA EV9?",
  "what is the best year to buy KIA EV6?",
  "what is the best year to buy KIA EV3?",
  "what is the best year to buy KIA SELTOS?",
  "what is the best year to buy KIA STONIC?",
  "what is the best year to buy KIA SORENTO?",
  "what is the best year to buy KIA SPORTAGE?",
  "what is the best year to buy KIA NIRO?",
  "what is the best year to buy KIA XCEED?",
  "what is the best year to buy KIA CEED?",
  "what is the best year to buy KIA RIO?",
  "what is the best year to buy KIA PICANTO?",
  "how long does it take to charge KIA PICANTO?",
  "what do KIA K4 owners complain about?",
  "what do KIA EV9 owners complain about?",
  "what do KIA EV6 owners complain about?",
  "what do KIA EV5 owners complain about?",
  "what do KIA EV4 owners complain about?",
  "what do KIA EV2 owners complain about?",
  "what do KIA SELTOS owners complain about?",
  "what do KIA STONIC owners complain about?",
  "what do KIA SORENTO owners complain about?",
  "what do KIA SPORTAGE owners complain about?",
  "what do KIA NIRO owners complain about?",
  "what do KIA XCEED owners complain about?",
  "what do KIA PROCEED owners complain about?",
  "what do KIA CEED owners complain about?",
  "what do KIA RIO owners complain about?",
  "what do KIA PICANTO owners complain about?",
  "what are common issues with KIA PV?",
  "what are common issues with KIA K4?",
  "what are common issues with KIA EV9?",
  "what are common issues with KIA EV6?",
  "what are common issues with KIA EV5?",
  "what are common issues with KIA EV4?",
  "what are common issues with KIA EV3?",
  "what are common issues with KIA EV2?",
  "what are common issues with KIA SELTOS?",
  "what are common issues with KIA STONIC?",
  "what are common issues with KIA SORENTO?",
  "what are common issues with KIA SPORTAGE?",
  "what are common issues with KIA NIRO?",
  "what are common issues with KIA XCEED?",
  "what are common issues with KIA CEED?",
  "what are common issues with KIA RIO?",
  "what are common issues with KIA PICANTO?",
  "what problems does KIA PV have?",
  "what problems does KIA K4 have?",
  "what problems does KIA EV9 have?",
  "what problems does KIA EV6 have?",
  "what problems does KIA EV5 have?",
  "what problems does KIA EV4 have?",
  "what problems does KIA EV3 have?",
  "what problems does KIA EV2 have?",
  "what problems does KIA SELTOS have?",
  "what problems does KIA STONIC have?",
  "what problems does KIA SORENTO have?",
  "what problems does KIA SPORTAGE have?",
  "what problems does KIA NIRO have?",
  "what problems does KIA XCEED have?",
  "what problems does KIA PROCEED have?",
  "what problems does KIA CEED have?",
  "what problems does KIA RIO have?",
  "is KIA EV9 reliable long term?",
  "is KIA EV6 reliable long term?",
  "is KIA EV4 reliable long term?",
  "is KIA EV3 reliable long term?",
  "is KIA EV2 reliable long term?",
  "is KIA SELTOS reliable long term?",
  "is KIA STONIC reliable long term?",
  "is KIA SORENTO reliable long term?",
  "is KIA NIRO reliable long term?",
  "is KIA XCEED reliable long term?",
  "is KIA PROCEED reliable long term?",
  "is KIA CEED reliable long term?",
  "is KIA EV9 reliable?",
  "is KIA EV6 reliable?",
  "is KIA EV4 reliable?",
  "is KIA EV3 reliable?",
  "is KIA EV2 reliable?",
  "is KIA SELTOS reliable?",
  "is KIA SORENTO reliable?",
  "is KIA NIRO reliable?",
  "is KIA PROCEED reliable?",
  "is KIA RIO reliable?",
  "is KIA PICANTO reliable?",
  "should i buy a KIA SELTOS?",
  "should i buy a KIA NIRO?",
  "should i buy a KIA RIO?",
  "is KIA SELTOS a good car?",
  "is KIA SORENTO a good car?",
  "is KIA NIRO a good car?",
  "is KIA EV9 worth buying?",
  "is KIA SORENTO worth buying?",
  "is KIA NIRO worth buying?",
  "is KIA or Toyota better for families?",
  "is KIA or Toyota service better?",
  "is KIA or Hyundai service better?",
  "which has better build quality, KIA or Renault?",
  "which is more reliable, KIA or Mazda.?",
  "is KIA or Mazda. more reliable?",
  "is KIA or Renault more reliable?",
  "is KIA or Toyota more reliable?",
  "is KIA or Hyundai more reliable?",
  "KIA vs Ford, which should i buy?",
  "should i buy KIA or MG?",
  "should i buy KIA or Volkswagen?",
  "should i buy KIA or Hyundai?",
  "which is better, KIA or Volkswagen?",
  "is KIA or Hyundai better?",
  "what electric car should i buy with a budget of 40,000?",
  "what problems do KIA forums report?",
  "what do KIA Facebook groups say?",
  "is KIA extended warranty worth it?",
  "is it hard to get warranty service from KIA?",
  "does KIA deny warranty claims?",
  "does KIA honor their warranty?",
  "how long is KIA warranty?",
  "what does KIA warranty cover?",
  "is KIA warranty good?",
  "can you negotiate the price of a KIA?",
  "is the KIA buying process a hassle?",
  "is KIA getting better or worse as a company?",
  "is KIA losing customers because of the CEO?",
  "is KIA reputation hurting because of the CEO?",
  "is KIA CEO controversy a reason not to buy?",
  "does KIA CEO affect if i should buy the car?",
  "should i avoid KIA because of the CEO?",
  "will i regret switching to an electric car?",
  "are Chinese electric cars safe?",
  "are Chinese electric cars good?",
  "are Chinese electric cars reliable?",
  "is KIA worth buying in United Kingdom?",
  "why do people get rid of their KIA?",
  "why are so many people selling their KIA?",
  "what are reasons not to buy a KIA?",
  "why should i not buy a KIA?",
  "should i avoid KIA?",
  "why do people regret buying KIA?",
  "have KIA cars killed anyone?",
  "do KIA cars leave you stranded?",
  "do KIA cars break down on the road?",
  "do people get stranded with KIA?",
  "i heard KIA batteries catch fire, is that true?",
  "i heard KIA quality has gotten worse, is that true?",
  "what does reddit say about buying a KIA?",
  "what problems do reddit users report with KIA?",
  "what do KIA owners on reddit complain about?",
  "what does reddit say about KIA?",
  "what do KIA owners hate about their car?",
  "what's the best part of owning a KIA?",
  "what's it like owning a KIA long term?",
  "honest KIA review after 2 years",
  "honest KIA review after 1 year",
  "do KIA owners regret their purchase?",
  "do people regret buying KIA?",
  "should i buy a used KIA or a new cheaper EV?",
  "what problems should i look for in a used KIA?",
  "what are the red flags when buying a used KIA?",
  "is a 2020 KIA still worth buying?",
  "is a 2018 KIA still worth buying?",
  "what year KIA should i avoid?",
  "what to look for when buying a used KIA?",
  "what should i check before buying a used KIA?",
  "is buying a used KIA risky?",
  "is a used KIA worth buying?",
  "is KIA still worth buying in 2024?",
  "should i buy a KIA now or wait?",
  "have KIA cars been in accidents because of defects?",
  "has KIA had safety issues?",
  "is KIA safe for children?",
  "is KIA safe for families?",
  "what is KIA safety rating?",
  "how did KIA do in crash tests?",
  "are KIA cars safe?",
  "is KIA safe?",
  "is KIA build quality getting better?",
  "is KIA paint quality bad?",
  "does KIA have paint problems?",
  "does KIA have fit and finish problems?",
  "does KIA have build quality problems?",
];
